
const MAX_POPUP_WIDTH = 800;
const MAX_POPUP_HEIGHT = 600;

const MAX_SEARCH_HISTORY = 50;
const MAX_EXPLORE_HISTORY = 25;

const INCREMENTAL_SEARCH_TIMEOUT_DELAY = 500;
const PREVIEW_TIMEOUT_DELAY = 300;

const DEFAULT_ICON_SEARCH_MODE = "normal";
const DEFAULT_ICON_FOLDER_MODE = "children";
const DEFAULT_ICON_SORT_MODE = "hierarchy";
const DEFAULT_WARNING_COUNT = 500;
const DEFAULT_BADGE_DISPLAY_MODE = "domain";


